#!/usr/bin/env python3
"""Aggregate retained negative and sensitivity cases for the appendix."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
RHO_METRIC = ROOT / "outputs/gpde_pndm_rho_metric_ablation_nfe5_10_15/gpde_pndm_rho_metric_ablation/metrics/gpde_pndm_rho_metric_ablation.csv"
AGGREGATION = ROOT / "outputs/gpde_pndm_aggregation_ablation_nfe5_10_15/gpde_pndm_aggregation_ablation/metrics/gpde_pndm_aggregation_ablation.csv"
T2I_PAIRWISE = ROOT / "paper/results/t2i/sd15_euler_nfe10_cfg_sweep_pairwise_summary.csv"

OUT_DIR = ROOT / "paper/results/failure"
TABLE_DIR = ROOT / "paper/tables"
OUT_CSV = OUT_DIR / "failure_cases_summary.csv"
OUT_TEX = TABLE_DIR / "failure_cases_summary.tex"


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def fid_row(rows: list[dict[str, str]], *, nfe: int, clock_label: str | None = None, family: str | None = None) -> dict[str, str]:
    for row in rows:
        if int(float(row["nfe"])) != nfe:
            continue
        if clock_label is not None and row["clock_label"] != clock_label:
            continue
        if family is not None and row["clock_family"] != family:
            continue
        return row
    raise KeyError((nfe, clock_label, family))


def t2i_row(rows: list[dict[str, str]], *, cfg: str, comparison: str) -> dict[str, str]:
    for row in rows:
        if row["guidance_scale"] == cfg and row["comparison"] == comparison:
            return row
    raise KeyError((cfg, comparison))


def fmt_signed(value: float) -> str:
    return f"{value:+.3f}"


def latex_escape(text: str) -> str:
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def main() -> None:
    rho_rows = read_rows(RHO_METRIC)
    agg_rows = read_rows(AGGREGATION)
    t2i_rows = read_rows(T2I_PAIRWISE)

    base10 = float(fid_row(rho_rows, nfe=10, family="base")["fid"])
    rho0_10 = float(fid_row(rho_rows, nfe=10, clock_label="rho_0")["fid"])
    edm10 = float(fid_row(rho_rows, nfe=10, clock_label="metric_edm_scalar")["fid"])

    cvar15 = float(fid_row(agg_rows, nfe=15, clock_label="aggregation_cvar")["fid"])
    mean15 = float(fid_row(agg_rows, nfe=15, clock_label="aggregation_mean")["fid"])

    records = [
        {
            "case": "rho=0 geometry",
            "setting": "PNDM/CIFAR-10 Euler, NFE 10, seed 0, 5k samples",
            "comparison": "D-GPDE rho=0 - base",
            "metric": "FID (lower better)",
            "delta": fmt_signed(rho0_10 - base10),
            "takeaway": "Removing the residual mix makes FID much worse than base.",
            "source": str(RHO_METRIC.relative_to(ROOT)),
        },
        {
            "case": "EDM scalar metric",
            "setting": "PNDM/CIFAR-10 Euler, NFE 10, seed 0, 5k samples",
            "comparison": "D-GPDE EDM scalar - base",
            "metric": "FID (lower better)",
            "delta": fmt_signed(edm10 - base10),
            "takeaway": "This metric variant loses the base-schedule gain.",
            "source": str(RHO_METRIC.relative_to(ROOT)),
        },
        {
            "case": "Mean aggregation",
            "setting": "PNDM/CIFAR-10 Euler, NFE 15, seed 0, 5k samples",
            "comparison": "mean - CVaR",
            "metric": "FID (lower better)",
            "delta": fmt_signed(mean15 - cvar15),
            "takeaway": "Mean aggregation remains positive but trails CVaR.",
            "source": str(AGGREGATION.relative_to(ROOT)),
        },
    ]

    for cfg in ("5", "7.5", "10"):
        row = t2i_row(t2i_rows, cfg=cfg, comparison="D-GPDE - base")
        records.append(
            {
                "case": f"SD1.5 CFG {cfg}",
                "setting": "SD1.5 Euler, NFE 10, 3 seeds, 50 prompts per seed",
                "comparison": "D-GPDE - base",
                "metric": "ImageReward (higher better)",
                "delta": fmt_signed(float(row["image_reward_mean_delta"])),
                "takeaway": "Matched text-to-image calibration lowers ImageReward.",
                "source": str(T2I_PAIRWISE.relative_to(ROOT)),
            }
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(records[0].keys()))
        writer.writeheader()
        writer.writerows(records)

    with OUT_TEX.open("w") as f:
        f.write("% Auto-generated by paper/figures/src/aggregate_failure_cases.py\n")
        f.write("\\begin{table}[t]\n")
        f.write("\\centering\n")
        f.write("\\caption{Retained failure and sensitivity cases. Positive FID deltas are worse; negative ImageReward deltas are worse.}\n")
        f.write("\\label{tab:failure-cases-summary}\n")
        f.write("\\scriptsize\n")
        f.write("\\setlength{\\tabcolsep}{3pt}\n")
        f.write("\\begin{tabular}{p{0.13\\linewidth}p{0.21\\linewidth}p{0.16\\linewidth}p{0.13\\linewidth}rp{0.15\\linewidth}}\n")
        f.write("\\toprule\n")
        f.write("Case & Setting & Comparison & Metric & Delta & Takeaway \\\\\n")
        f.write("\\midrule\n")
        for record in records:
            f.write(
                " & ".join(
                    [
                        latex_escape(record["case"]),
                        latex_escape(record["setting"]),
                        latex_escape(record["comparison"]).replace("D-GPDE", r"\method{}"),
                        latex_escape(record["metric"]),
                        record["delta"],
                        latex_escape(record["takeaway"]),
                    ]
                )
                + " \\\\\n"
            )
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")


if __name__ == "__main__":
    main()
